//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantys.Workflow.Applications.MicrosoftGraph {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimeZoneCustom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeZoneCustom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advantys.Workflow.Applications.MicrosoftGraph.TimeZoneCustom", typeof(TimeZoneCustom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/Berlin.
        /// </summary>
        internal static string GMT0100AmsterdamBerlinBernRomeStockholmVienna {
            get {
                return ResourceManager.GetString("GMT0100AmsterdamBerlinBernRomeStockholmVienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantic/Azores.
        /// </summary>
        internal static string GMT0100Azores {
            get {
                return ResourceManager.GetString("GMT0100Azores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/Budapest.
        /// </summary>
        internal static string GMT0100BelgradeBratislavaBudapestLjubljanaPrague {
            get {
                return ResourceManager.GetString("GMT0100BelgradeBratislavaBudapestLjubljanaPrague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/Paris.
        /// </summary>
        internal static string GMT0100BrusselsCopenhagenMadridParis {
            get {
                return ResourceManager.GetString("GMT0100BrusselsCopenhagenMadridParis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantic/Cape_Verde.
        /// </summary>
        internal static string GMT0100CapeVerdeIs {
            get {
                return ResourceManager.GetString("GMT0100CapeVerdeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/Warsaw.
        /// </summary>
        internal static string GMT0100SarajevoSkopjeWarsawZagreb {
            get {
                return ResourceManager.GetString("GMT0100SarajevoSkopjeWarsawZagreb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/Budapest.
        /// </summary>
        internal static string GMT0100WestCentralAfrica {
            get {
                return ResourceManager.GetString("GMT0100WestCentralAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Amman.
        /// </summary>
        internal static string GMT0200Amman {
            get {
                return ResourceManager.GetString("GMT0200Amman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/Istanbul.
        /// </summary>
        internal static string GMT0200AthensIstanbulMinsk {
            get {
                return ResourceManager.GetString("GMT0200AthensIstanbulMinsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Beirut.
        /// </summary>
        internal static string GMT0200Beirut {
            get {
                return ResourceManager.GetString("GMT0200Beirut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/Bucharest.
        /// </summary>
        internal static string GMT0200Bucharest {
            get {
                return ResourceManager.GetString("GMT0200Bucharest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa/Cairo.
        /// </summary>
        internal static string GMT0200Cairo {
            get {
                return ResourceManager.GetString("GMT0200Cairo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa/Cairo.
        /// </summary>
        internal static string GMT0200HararePretoria {
            get {
                return ResourceManager.GetString("GMT0200HararePretoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/Kyiv (Kiev).
        /// </summary>
        internal static string GMT0200HelsinkiKyivRigaSofiaTallinnVilnius {
            get {
                return ResourceManager.GetString("GMT0200HelsinkiKyivRigaSofiaTallinnVilnius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Jerusalem.
        /// </summary>
        internal static string GMT0200Jerusalem {
            get {
                return ResourceManager.GetString("GMT0200Jerusalem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa/Windhoek.
        /// </summary>
        internal static string GMT0200MidAtlantic {
            get {
                return ResourceManager.GetString("GMT0200MidAtlantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa/Windhoek.
        /// </summary>
        internal static string GMT0200Windhoek {
            get {
                return ResourceManager.GetString("GMT0200Windhoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Baghdad.
        /// </summary>
        internal static string GMT0300Baghdad {
            get {
                return ResourceManager.GetString("GMT0300Baghdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Sao_Paulo.
        /// </summary>
        internal static string GMT0300Brasilia {
            get {
                return ResourceManager.GetString("GMT0300Brasilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Argentina/Buenos_Aires.
        /// </summary>
        internal static string GMT0300BuenosAiresGeorgetown {
            get {
                return ResourceManager.GetString("GMT0300BuenosAiresGeorgetown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Montevideo.
        /// </summary>
        internal static string GMT0300Greenland {
            get {
                return ResourceManager.GetString("GMT0300Greenland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Riyadh.
        /// </summary>
        internal static string GMT0300KuwaitRiyadh {
            get {
                return ResourceManager.GetString("GMT0300KuwaitRiyadh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Montevideo.
        /// </summary>
        internal static string GMT0300Montevideo {
            get {
                return ResourceManager.GetString("GMT0300Montevideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/Moscow.
        /// </summary>
        internal static string GMT0300MoscowStPetersburgVolgograd {
            get {
                return ResourceManager.GetString("GMT0300MoscowStPetersburgVolgograd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa/Nairobi.
        /// </summary>
        internal static string GMT0300Nairobi {
            get {
                return ResourceManager.GetString("GMT0300Nairobi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Tbilisi.
        /// </summary>
        internal static string GMT0300Tbilisi {
            get {
                return ResourceManager.GetString("GMT0300Tbilisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Sao_Paulo.
        /// </summary>
        internal static string GMT0330Newfoundland {
            get {
                return ResourceManager.GetString("GMT0330Newfoundland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Tehran.
        /// </summary>
        internal static string GMT0330Tehran {
            get {
                return ResourceManager.GetString("GMT0330Tehran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Yerevan.
        /// </summary>
        internal static string GMT0400AbuDhabiMuscat {
            get {
                return ResourceManager.GetString("GMT0400AbuDhabiMuscat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Santiago.
        /// </summary>
        internal static string GMT0400AtlanticTimeCanada {
            get {
                return ResourceManager.GetString("GMT0400AtlanticTimeCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Baku.
        /// </summary>
        internal static string GMT0400Baku {
            get {
                return ResourceManager.GetString("GMT0400Baku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Caracas.
        /// </summary>
        internal static string GMT0400CaracasLaPaz {
            get {
                return ResourceManager.GetString("GMT0400CaracasLaPaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Santiago.
        /// </summary>
        internal static string GMT0400Manaus {
            get {
                return ResourceManager.GetString("GMT0400Manaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Santiago.
        /// </summary>
        internal static string GMT0400Santiago {
            get {
                return ResourceManager.GetString("GMT0400Santiago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Yerevan.
        /// </summary>
        internal static string GMT0400Yerevan {
            get {
                return ResourceManager.GetString("GMT0400Yerevan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Kabul.
        /// </summary>
        internal static string GMT0430Kabul {
            get {
                return ResourceManager.GetString("GMT0430Kabul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Bogota.
        /// </summary>
        internal static string GMT0500BogotaLimaQuitoRioBranco {
            get {
                return ResourceManager.GetString("GMT0500BogotaLimaQuitoRioBranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/New_York.
        /// </summary>
        internal static string GMT0500EasternTimeUSandCanada {
            get {
                return ResourceManager.GetString("GMT0500EasternTimeUSandCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Karachi.
        /// </summary>
        internal static string GMT0500Ekaterinburg {
            get {
                return ResourceManager.GetString("GMT0500Ekaterinburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Indiana/Indianapolis.
        /// </summary>
        internal static string GMT0500IndianaEast {
            get {
                return ResourceManager.GetString("GMT0500IndianaEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Karachi.
        /// </summary>
        internal static string GMT0500IslamabadKarachiTashkent {
            get {
                return ResourceManager.GetString("GMT0500IslamabadKarachiTashkent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Kolkata.
        /// </summary>
        internal static string GMT0530ChennaiKolkataMumbaiNewDelhi {
            get {
                return ResourceManager.GetString("GMT0530ChennaiKolkataMumbaiNewDelhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Kathmandu.
        /// </summary>
        internal static string GMT0545Kathmandu {
            get {
                return ResourceManager.GetString("GMT0545Kathmandu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Astana (Almaty).
        /// </summary>
        internal static string GMT0600AlmatyNovosibirsk {
            get {
                return ResourceManager.GetString("GMT0600AlmatyNovosibirsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Dhaka.
        /// </summary>
        internal static string GMT0600AstanaDhaka {
            get {
                return ResourceManager.GetString("GMT0600AstanaDhaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Chicago.
        /// </summary>
        internal static string GMT0600CentralAmerica {
            get {
                return ResourceManager.GetString("GMT0600CentralAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Chicago.
        /// </summary>
        internal static string GMT0600CentralTimeUSandCanada {
            get {
                return ResourceManager.GetString("GMT0600CentralTimeUSandCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Mexico_City.
        /// </summary>
        internal static string GMT0600GuadalajaraMexicoCityMonterrey {
            get {
                return ResourceManager.GetString("GMT0600GuadalajaraMexicoCityMonterrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Mexico_City.
        /// </summary>
        internal static string GMT0600Saskatchewan {
            get {
                return ResourceManager.GetString("GMT0600Saskatchewan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Dhaka.
        /// </summary>
        internal static string GMT0600SriJayawardenepura {
            get {
                return ResourceManager.GetString("GMT0600SriJayawardenepura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Yangon (Rangoon).
        /// </summary>
        internal static string GMT0630Rangoon {
            get {
                return ResourceManager.GetString("GMT0630Rangoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Chihuahua.
        /// </summary>
        internal static string GMT0700Arizona {
            get {
                return ResourceManager.GetString("GMT0700Arizona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Bangkok.
        /// </summary>
        internal static string GMT0700BangkokHanoiJakarta {
            get {
                return ResourceManager.GetString("GMT0700BangkokHanoiJakarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Chihuahua.
        /// </summary>
        internal static string GMT0700ChihuahuaLaPazMazatlan {
            get {
                return ResourceManager.GetString("GMT0700ChihuahuaLaPazMazatlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Krasnoyarsk.
        /// </summary>
        internal static string GMT0700Krasnoyarsk {
            get {
                return ResourceManager.GetString("GMT0700Krasnoyarsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Chihuahua.
        /// </summary>
        internal static string GMT0700MountainTimeUSandCanada {
            get {
                return ResourceManager.GetString("GMT0700MountainTimeUSandCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Singapore.
        /// </summary>
        internal static string GMT0800BeijingChongqingHongKongUrumqi {
            get {
                return ResourceManager.GetString("GMT0800BeijingChongqingHongKongUrumqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Irkutsk.
        /// </summary>
        internal static string GMT0800IrkutskUlaanBataar {
            get {
                return ResourceManager.GetString("GMT0800IrkutskUlaanBataar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Singapore.
        /// </summary>
        internal static string GMT0800KualaLumpurSingapore {
            get {
                return ResourceManager.GetString("GMT0800KualaLumpurSingapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Los_Angeles.
        /// </summary>
        internal static string GMT0800PacificTimeUSandCanada {
            get {
                return ResourceManager.GetString("GMT0800PacificTimeUSandCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia/Perth.
        /// </summary>
        internal static string GMT0800Perth {
            get {
                return ResourceManager.GetString("GMT0800Perth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Taipei.
        /// </summary>
        internal static string GMT0800Taipei {
            get {
                return ResourceManager.GetString("GMT0800Taipei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Los_Angeles.
        /// </summary>
        internal static string GMT0800TijuanaBajaCalifornia {
            get {
                return ResourceManager.GetString("GMT0800TijuanaBajaCalifornia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/Anchorage.
        /// </summary>
        internal static string GMT0900Alaska {
            get {
                return ResourceManager.GetString("GMT0900Alaska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Tokyo.
        /// </summary>
        internal static string GMT0900OsakaSapporoTokyo {
            get {
                return ResourceManager.GetString("GMT0900OsakaSapporoTokyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Seoul.
        /// </summary>
        internal static string GMT0900Seoul {
            get {
                return ResourceManager.GetString("GMT0900Seoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Yakutsk.
        /// </summary>
        internal static string GMT0900Yakutsk {
            get {
                return ResourceManager.GetString("GMT0900Yakutsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia/Adelaide.
        /// </summary>
        internal static string GMT0930Adelaide {
            get {
                return ResourceManager.GetString("GMT0930Adelaide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia/Darwin.
        /// </summary>
        internal static string GMT0930Darwin {
            get {
                return ResourceManager.GetString("GMT0930Darwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia/Brisbane.
        /// </summary>
        internal static string GMT1000Brisbane {
            get {
                return ResourceManager.GetString("GMT1000Brisbane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia/Sydney.
        /// </summary>
        internal static string GMT1000CanberraMelbourneSydney {
            get {
                return ResourceManager.GetString("GMT1000CanberraMelbourneSydney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific/Port_Moresby.
        /// </summary>
        internal static string GMT1000GuamPortMoresby {
            get {
                return ResourceManager.GetString("GMT1000GuamPortMoresby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific/Honolulu.
        /// </summary>
        internal static string GMT1000Hawaii {
            get {
                return ResourceManager.GetString("GMT1000Hawaii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia/Hobart.
        /// </summary>
        internal static string GMT1000Hobart {
            get {
                return ResourceManager.GetString("GMT1000Hobart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Vladivostok.
        /// </summary>
        internal static string GMT1000Vladivostok {
            get {
                return ResourceManager.GetString("GMT1000Vladivostok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia/Magadan.
        /// </summary>
        internal static string GMT1100MagadanSolomonIsNewCaledonia {
            get {
                return ResourceManager.GetString("GMT1100MagadanSolomonIsNewCaledonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific/Honolulu.
        /// </summary>
        internal static string GMT1100MidwayIslandSamoa {
            get {
                return ResourceManager.GetString("GMT1100MidwayIslandSamoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific/Auckland.
        /// </summary>
        internal static string GMT1200AucklandWellington {
            get {
                return ResourceManager.GetString("GMT1200AucklandWellington", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific/Fiji.
        /// </summary>
        internal static string GMT1200FijiIsKamchatkaMarshallIs {
            get {
                return ResourceManager.GetString("GMT1200FijiIsKamchatkaMarshallIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etc/GMT-12.
        /// </summary>
        internal static string GMT1200InternationalDateLineWest {
            get {
                return ResourceManager.GetString("GMT1200InternationalDateLineWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific/Fiji.
        /// </summary>
        internal static string GMT1300Nukualofa {
            get {
                return ResourceManager.GetString("GMT1300Nukualofa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa/Casablanca.
        /// </summary>
        internal static string GMTCasablancaMonrovia {
            get {
                return ResourceManager.GetString("GMTCasablancaMonrovia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe/London.
        /// </summary>
        internal static string GMTGreenwichMeanTimeDublinEdinburghLisbonLondon {
            get {
                return ResourceManager.GetString("GMTGreenwichMeanTimeDublinEdinburghLisbonLondon", resourceCulture);
            }
        }
    }
}
